-- Add migration script here
CREATE TABLE IF NOT EXISTS users (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	role INT(11) NOT NULL DEFAULT 1,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password CHAR(60) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, name, email, password) VALUES (
	'admin',
	'Administrator',
	'admin@change.me',
	'$2b$10$DQNu./bivFUXpXWe2a9gC.CKPCx9Sy8/b2FMIdyctUNAXsJgFgI2G' -- rustime
);

CREATE TABLE IF NOT EXISTS settings (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	enabled TINYINT(1) NOT NULL DEFAULT 1,
	cron VARCHAR(255) NOT NULL,
	target VARCHAR(255) NOT NULL,
	method TINYINT NOT NULL DEFAULT 1,
	is_up TINYINT(1) NOT NULL DEFAULT 1,
	last_down DATETIME,
	down_reason VARCHAR(255),
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type INT(11) NOT NULL,
	linked_id INT(11),
	run_at DATETIME NOT NULL,
	INDEX idx_run_at (run_at)
);
